function [zdot, T1, T2] = FullDyn(t,z,p,implementation_toggle)
%FULDYN Full dynamics for the double pendulum. Uses autogenerated Thdotdot1
%and 2.
th1 = z(1);
th2 = z(3);
thdot1 = z(2);
thdot2 = z(4);
% Fdx = 0;
% Fdy = 0;

%Current disturbance force on end effector
FxCurrent = p.Fx;
FyCurrent = p.Fy;

%Current Target
xCurrentTar = p.xtarget;
yCurrentTar = p.ytarget;

xdotCurrentTar = 0;
ydotCurrentTar = 0;

T         = zeros(2,1);
T1        = zeros(1,1);
T2        = zeros(1,1);
thdotdot1 = zeros(1,1);
thdotdot2 = zeros(1,1);
if implementation_toggle == true
    %Torque to track our desired point
    T = ImpedenceControl(p.Kd,p.Kp,p.l1,p.l2,th1,th2,thdot1,thdot2,xdotCurrentTar,xCurrentTar,ydotCurrentTar,yCurrentTar);
    
    %Add gravity compensation
    T1 = T(1) + GravityCompT1(0,0,p.d1,p.d2,p.g,p.l1,p.l2,p.m1,p.m2,th1,th2,thdot1,thdot2);
    T2 = T(2) + GravityCompT2(0,0,p.d2,p.g,p.l1,p.l2,p.m2,th1,th2,thdot1);
    
    %Use the autoderived functions for the accelerations. 
    thdotdot1 = Thdotdot1(FxCurrent,FyCurrent,p.I1,p.I2,T1,T2,p.d1,p.d2,p.g,p.l1,p.l2,p.m1,p.m2,th1,th2,thdot1,thdot2);
    thdotdot2 = Thdotdot2(FxCurrent,FyCurrent,p.I1,p.I2,T1,T2,p.d1,p.d2,p.g,p.l1,p.l2,p.m1,p.m2,th1,th2,thdot1,thdot2);
else
    % TODO: Replace ImpedenceControl with my own implementation
    [q1, q2] = CoordinateTransform(th1,th2); % Note that [qdot1,qdot2] == [thdot1,thdot2]
    [T,thdotdot] = impedance_controller_mex([0,p.Kd,p.Kp,0], ...
        [p.m1,p.m2], [p.l1,p.l2], [p.d1,p.d2], 120, ...
        [q1,q2], [thdot1,thdot2], ...
        [xCurrentTar,yCurrentTar], [xdotCurrentTar,ydotCurrentTar], [0,0], ...
        [0,0]);

    % TODO: Replace GravityCompT1 and GravityCompT2 with my own implementation
    % G  = gravity_compensation_mex([p.m1,p.m2], [p.l1,p.l2], [p.d1,p.d2], ...
    %     [th1,th2]);
    % T1 = T(1) + G(1);
    % T2 = T(2) + G(2);
    T1 = T(1) + GravityCompT1(0,0,p.d1,p.d2,p.g,p.l1,p.l2,p.m1,p.m2,th1,th2,thdot1,thdot2);
    T2 = T(2) + GravityCompT2(0,0,p.d2,p.g,p.l1,p.l2,p.m2,th1,th2,thdot1);

    % TODO: Replace Thdotdot1 and Thdotdot2 with my own implementation
    % thdotdot1 = thdotdot(1);
    % thdotdot2 = thdotdot(2);
    thdotdot1 = Thdotdot1(FxCurrent,FyCurrent,p.I1,p.I2,T1,T2,p.d1,p.d2,p.g,p.l1,p.l2,p.m1,p.m2,th1,th2,thdot1,thdot2);
    thdotdot2 = Thdotdot2(FxCurrent,FyCurrent,p.I1,p.I2,T1,T2,p.d1,p.d2,p.g,p.l1,p.l2,p.m1,p.m2,th1,th2,thdot1,thdot2);
end

%Assemble the state vector derivatives.
zdot = [thdot1
    thdotdot1
    thdot2
    thdotdot2
    ];

end

