#########################################
#                                       #
#    IMPEDANCE CONTROLLER PARAMETERS    #
#                                       #
#########################################

# Virtual inertia matrix (2x2)
virtual_inertia_matrix = [
    [0.0, 0.0],
    [0.0, 0.0]
]

# Virtual damping matrix (2x2)
virtual_damping_matrix = [
    [8.0, 0.0],
    [0.0, 8.0]
]

# Virtual stiffness matrix (2x2)
virtual_stiffness_matrix = [
    [10.0, 0.0],
    [0.0, 10.0]
]

# Force feedback gain (scalar)
force_feedback_gain = 0.0

# Control loop duration (scalar) in ms
control_loop_duration = 10

###############################
#                             #
#    MECHANICAL PARAMETERS    #
#                             #
###############################

# Link mass vector (2x1) in kg
link_mass_vector = [3.4, 1.37]

# Link length vector (2x1) in m
link_length_vector = [0.35, 0.38]

# Distance to link CoM vector (2x1) in m
dist_to_com_vector = [0.28, 0.19]

##########################
#                        #
#    MOTOR PARAMETERS    #
#                        #
##########################

# Maximal torque (scalar) in Nm
max_actuator_torque = 10