<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>impedance_controller</name>
  <version>0.1.0</version>
  <description>This pkg reads trajectory and sensor data to generate a torque command for the SeaClear grapple fingers.</description>
  <maintainer email="lucasmo.silva@tum.de">Lucas M. O. Silva</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rclcpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <!-- <build_depend>impedance_controller_msgs</build_depend> This package is not yet needed, but might be in the future when we add custom messages. -->

  <!-- <exec_depend>impedance_controller_msgs</exec_depend> See comment about this pkg above. -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_ros</test_depend>
  <test_depend>launch</test_depend>
  <test_depend>launch_ros</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>rclpy</test_depend>

  <depend>ament_index_cpp</depend>
  <depend>impedance_controller_params</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
